namespace PublicationQualitySystem.Domain.Enums;

public enum ProcessingStep
{
    FILE_UPLOADED = 0,
    FILE_VALIDATED = 1,
    S3_UPLOADED = 2,
    UPLOADED_FILE_CREATED = 3,
    PAPER_CREATED = 4,
    PAPER_VERSION_CREATED = 5,
    GROBID_METADATA_EXTRACTION = 6,
    NOUGAT_MARKDOWN_CONVERSION = 7,
    SECTION_EXTRACTION = 8,
    AI_QUALITY_REVIEW = 9,
    METADATA_QUALITY_SCORING = 10,
    INTEGRITY_SCREENING = 11,
    RISK_CLASSIFICATION = 12,
    REPORT_GENERATION = 13
}
