using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PublicationQualitySystem.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RefactorPaperProcessingTrackerToWorkflowEvents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                alter table paper_processing_trackers
                    add column if not exists current_stage character varying(100) not null default 'UPLOADED';

                alter table paper_processing_trackers
                    add column if not exists current_status character varying(50) not null default 'PENDING';

                alter table paper_processing_trackers
                    add column if not exists overall_status character varying(50) not null default 'PENDING';

                alter table paper_processing_trackers
                    add column if not exists last_error character varying(1000);

                update paper_processing_trackers
                set current_stage = 'UPLOADED'
                where current_stage is null or btrim(current_stage) = '';

                update paper_processing_trackers
                set current_status = 'PENDING'
                where current_status is null or btrim(current_status) = '';

                update paper_processing_trackers
                set overall_status = case lower(overall_status)
                    when 'pending' then 'PENDING'
                    when 'processing' then 'PROCESSING'
                    when 'completed' then 'COMPLETED'
                    when 'failed' then 'FAILED'
                    else coalesce(nullif(overall_status, ''), 'PENDING')
                end;

                alter table paper_processing_trackers
                    alter column current_stage set default 'UPLOADED',
                    alter column current_stage set not null,
                    alter column current_status set default 'PENDING',
                    alter column current_status set not null,
                    alter column overall_status set default 'PENDING',
                    alter column overall_status set not null;

                alter table paper_processing_trackers alter column current_step set default 'Upload';
                alter table paper_processing_trackers alter column upload_status set default 'Completed';
                alter table paper_processing_trackers alter column markdown_status set default 'NotStarted';
                alter table paper_processing_trackers alter column metadata_extraction_status set default 'NotStarted';
                alter table paper_processing_trackers alter column metadata_quality_status set default 'NotStarted';
                alter table paper_processing_trackers alter column openalex_status set default 'NotStarted';
                alter table paper_processing_trackers alter column crossref_status set default 'NotStarted';
                alter table paper_processing_trackers alter column ai_review_status set default 'NotStarted';
                alter table paper_processing_trackers alter column integrity_screening_status set default 'NotStarted';
                """);

            migrationBuilder.Sql("""
                create table if not exists paper_processing_events (
                    "Id" bigint generated by default as identity,
                    paper_id bigint not null,
                    paper_version_id bigint not null,
                    tracker_id bigint not null,
                    event_id character varying(100),
                    event_type character varying(255) not null,
                    stage character varying(100) not null,
                    status character varying(50) not null,
                    payload_json jsonb,
                    error_message character varying(4000),
                    "CreatedAt" timestamp with time zone not null,
                    "UpdatedAt" timestamp with time zone not null,
                    "Deleted" boolean not null default false,
                    "CreatedBy" text,
                    "UpdatedBy" text,
                    constraint "PK_paper_processing_events" primary key ("Id"),
                    constraint "FK_paper_processing_events_paper_processing_trackers_tracker_id"
                        foreign key (tracker_id) references paper_processing_trackers ("Id") on delete cascade,
                    constraint "FK_paper_processing_events_paper_versions_paper_version_id"
                        foreign key (paper_version_id) references paper_versions ("Id") on delete cascade,
                    constraint "FK_paper_processing_events_papers_paper_id"
                        foreign key (paper_id) references papers ("Id") on delete cascade
                );
                """);

            migrationBuilder.Sql("""
                create index if not exists "IX_paper_processing_trackers_current_status"
                    on paper_processing_trackers (current_status);
                create index if not exists "IX_paper_processing_events_created_at"
                    on paper_processing_events ("CreatedAt");
                create index if not exists "IX_paper_processing_events_event_id"
                    on paper_processing_events (event_id);
                create index if not exists "IX_paper_processing_events_event_type"
                    on paper_processing_events (event_type);
                create index if not exists "IX_paper_processing_events_paper_id"
                    on paper_processing_events (paper_id);
                create index if not exists "IX_paper_processing_events_paper_version_id"
                    on paper_processing_events (paper_version_id);
                create index if not exists "IX_paper_processing_events_stage"
                    on paper_processing_events (stage);
                create index if not exists "IX_paper_processing_events_status"
                    on paper_processing_events (status);
                create index if not exists "IX_paper_processing_events_tracker_id"
                    on paper_processing_events (tracker_id);
                """);

            migrationBuilder.Sql("""
                with latest_events as (
                    select distinct on (tracker_id)
                        tracker_id,
                        stage,
                        status,
                        "CreatedAt"
                    from paper_processing_events
                    where not "Deleted"
                    order by tracker_id, "CreatedAt" desc, "Id" desc
                )
                update paper_processing_trackers tracker
                set current_stage = latest_events.stage,
                    current_status = latest_events.status,
                    overall_status = latest_events.status,
                    last_updated_at = latest_events."CreatedAt"
                from latest_events
                where tracker."Id" = latest_events.tracker_id;
                """);

            migrationBuilder.Sql("""
                with legacy as (
                    select
                        tracker."Id",
                        case
                            when lower(coalesce(overall_status, '')) = 'failed'
                              or lower(coalesce(markdown_status, '')) = 'failed'
                              or lower(coalesce(metadata_extraction_status, '')) = 'failed'
                              or lower(coalesce(metadata_quality_status, '')) = 'failed'
                              or lower(coalesce(openalex_status, '')) = 'failed'
                              or lower(coalesce(crossref_status, '')) = 'failed'
                              or lower(coalesce(ai_review_status, '')) = 'failed'
                              or lower(coalesce(integrity_screening_status, '')) = 'failed'
                                then 'FAILED'
                            when progress_percent >= 100 or lower(coalesce(overall_status, '')) = 'completed'
                                then 'COMPLETED'
                            when lower(coalesce(openalex_status, '')) = 'completed'
                                then 'OPENALEX_COMPLETED'
                            when lower(coalesce(openalex_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                                then 'OPENALEX_REQUESTED'
                            when lower(coalesce(metadata_quality_status, '')) = 'completed'
                                then 'QUALITY_SCORING_COMPLETED'
                            when lower(coalesce(metadata_quality_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                                then 'QUALITY_SCORING_REQUESTED'
                            when lower(coalesce(metadata_extraction_status, '')) = 'completed'
                                then 'METADATA_COMPLETED'
                            when lower(coalesce(metadata_extraction_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                                then 'METADATA_REQUESTED'
                            when lower(coalesce(markdown_status, '')) = 'completed'
                                then 'OCR_COMPLETED'
                            when lower(coalesce(markdown_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                                then 'OCR_REQUESTED'
                            else 'UPLOADED'
                        end as derived_stage,
                        case
                            when lower(coalesce(overall_status, '')) = 'failed'
                              or lower(coalesce(markdown_status, '')) = 'failed'
                              or lower(coalesce(metadata_extraction_status, '')) = 'failed'
                              or lower(coalesce(metadata_quality_status, '')) = 'failed'
                              or lower(coalesce(openalex_status, '')) = 'failed'
                              or lower(coalesce(crossref_status, '')) = 'failed'
                              or lower(coalesce(ai_review_status, '')) = 'failed'
                              or lower(coalesce(integrity_screening_status, '')) = 'failed'
                                then 'FAILED'
                            when progress_percent >= 100 or lower(coalesce(overall_status, '')) = 'completed'
                                then 'COMPLETED'
                            when lower(coalesce(overall_status, '')) = 'processing'
                              or lower(coalesce(markdown_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                              or lower(coalesce(metadata_extraction_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                              or lower(coalesce(metadata_quality_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                              or lower(coalesce(openalex_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                              or lower(coalesce(crossref_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                              or lower(coalesce(ai_review_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                              or lower(coalesce(integrity_screening_status, '')) in ('processing', 'eventpublished', 'retryscheduled')
                                then 'PROCESSING'
                            else 'PENDING'
                        end as derived_status
                    from paper_processing_trackers tracker
                    where not exists (
                        select 1
                        from paper_processing_events event
                        where event.tracker_id = tracker."Id"
                          and not event."Deleted"
                    )
                )
                update paper_processing_trackers tracker
                set current_stage = legacy.derived_stage,
                    current_status = legacy.derived_status,
                    overall_status = legacy.derived_status
                from legacy
                where tracker."Id" = legacy."Id";
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                drop table if exists paper_processing_events;
                drop index if exists "IX_paper_processing_trackers_current_status";
                alter table paper_processing_trackers drop column if exists current_stage;
                alter table paper_processing_trackers drop column if exists current_status;
                alter table paper_processing_trackers drop column if exists last_error;
                alter table paper_processing_trackers alter column overall_status set default 'Pending';
                """);
        }
    }
}
