// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PublicationQualitySystem.Infrastructure.Configurations;

#nullable disable

namespace PublicationQualitySystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<long?>("PaperId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_id");

                    b.Property<long?>("PaperVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_version_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long?>("UploadedFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_file_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaperId");

                    b.HasIndex("PaperVersionId");

                    b.HasIndex("Status");

                    b.HasIndex("Step");

                    b.HasIndex("UploadedFileId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.Paper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("papers", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<string>("ArxivId")
                        .HasColumnType("text")
                        .HasColumnName("arxiv_id");

                    b.Property<string>("AuthorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("authors_json");

                    b.Property<string>("ConferenceName")
                        .HasColumnType("text")
                        .HasColumnName("conference_name");

                    b.Property<string>("CorrespondingAuthor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("corresponding_author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("doi");

                    b.Property<string>("DoiSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("doi_source");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<string>("ExtractionError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("extraction_error");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FundingOrganizationsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("funding_organizations_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Issue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("issue");

                    b.Property<string>("Journal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("journal");

                    b.Property<string>("JournalSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("journal_source");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords_json");

                    b.Property<bool?>("MetadataQualityCanProceed")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_quality_can_proceed");

                    b.Property<int?>("MetadataQualityCoreScore")
                        .HasColumnType("integer")
                        .HasColumnName("metadata_quality_core_score");

                    b.Property<int?>("MetadataQualityEnrichmentScore")
                        .HasColumnType("integer")
                        .HasColumnName("metadata_quality_enrichment_score");

                    b.Property<int?>("MetadataQualityExtendedScore")
                        .HasColumnType("integer")
                        .HasColumnName("metadata_quality_extended_score");

                    b.Property<string>("MetadataQualityFieldScoresJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_quality_field_scores_json");

                    b.Property<string>("MetadataQualityGrade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metadata_quality_grade");

                    b.Property<string>("MetadataQualityMissingFieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_quality_missing_fields_json");

                    b.Property<DateTime?>("MetadataQualityScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_quality_scored_at");

                    b.Property<int?>("MetadataQualityTotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("metadata_quality_total_score");

                    b.Property<string>("MetadataQualityWarningsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_quality_warnings_json");

                    b.Property<string>("MetadataSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metadata_source");

                    b.Property<string>("Pages")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pages");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_id");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publisher");

                    b.Property<string>("RawGrobidXml")
                        .HasColumnType("text")
                        .HasColumnName("raw_grobid_xml");

                    b.Property<string>("ReferencesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("references_json");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasColumnType("text")
                        .HasColumnName("venue");

                    b.Property<string>("Volume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("PaperId")
                        .IsUnique();

                    b.ToTable("paper_metadata", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperProcessingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_type");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_id");

                    b.Property<long>("PaperVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_version_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<long>("TrackerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tracker_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventId");

                    b.HasIndex("EventType");

                    b.HasIndex("PaperId");

                    b.HasIndex("PaperVersionId");

                    b.HasIndex("Stage");

                    b.HasIndex("Status");

                    b.HasIndex("TrackerId");

                    b.ToTable("paper_processing_events", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperProcessingTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("UPLOADED")
                        .HasColumnName("current_stage");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("current_status");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("overall_status");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_id");

                    b.Property<long>("PaperVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_version_id");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("PaperId");

                    b.HasIndex("PaperVersionId")
                        .IsUnique();

                    b.ToTable("paper_processing_trackers", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperSimilarityCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AbstractSimilarity")
                        .HasColumnType("double precision")
                        .HasColumnName("abstract_similarity");

                    b.Property<double?>("AuthorSimilarity")
                        .HasColumnType("double precision")
                        .HasColumnName("author_similarity");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("MatchedDoi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("matched_doi");

                    b.Property<string>("MatchedOpenAlexId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("matched_openalex_id");

                    b.Property<string>("MatchedTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("matched_title");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_id");

                    b.Property<long>("PaperMetadataId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_metadata_id");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<double?>("ReferenceSimilarity")
                        .HasColumnType("double precision")
                        .HasColumnName("reference_similarity");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_level");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("skip_reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<double?>("TitleSimilarity")
                        .HasColumnType("double precision")
                        .HasColumnName("title_similarity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("PaperId");

                    b.HasIndex("PaperMetadataId");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("Source", "PaperMetadataId")
                        .IsUnique();

                    b.ToTable("paper_similarity_checks", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConversionError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("conversion_error");

                    b.Property<string>("ConversionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("conversion_status");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MarkdownS3Key")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("markdown_s3_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint")
                        .HasColumnName("paper_id");

                    b.Property<string>("PdfS3Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pdf_s3_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("PaperId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("paper_versions", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.Property<long>("permission_id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.HasKey("permission_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.Property<string>("user_id")
                        .HasColumnType("character varying(100)");

                    b.HasKey("role_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperMetadata", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Paper", "Paper")
                        .WithOne("Metadata")
                        .HasForeignKey("PublicationQualitySystem.Domain.Entities.PaperMetadata", "PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperProcessingEvent", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationQualitySystem.Domain.Entities.PaperVersion", "PaperVersion")
                        .WithMany()
                        .HasForeignKey("PaperVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationQualitySystem.Domain.Entities.PaperProcessingTracker", "Tracker")
                        .WithMany("Events")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("PaperVersion");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperProcessingTracker", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationQualitySystem.Domain.Entities.PaperVersion", "PaperVersion")
                        .WithMany()
                        .HasForeignKey("PaperVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("PaperVersion");
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperSimilarityCheck", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationQualitySystem.Domain.Entities.PaperMetadata", "PaperMetadata")
                        .WithMany()
                        .HasForeignKey("PaperMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("PaperMetadata");
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperVersion", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Paper", "Paper")
                        .WithMany("Versions")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationQualitySystem.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("PublicationQualitySystem.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationQualitySystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.Paper", b =>
                {
                    b.Navigation("Metadata");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PublicationQualitySystem.Domain.Entities.PaperProcessingTracker", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
